SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_TITLE = "Platformer Adventure"

TILE_SCALING = 0.5
PLAYER_SCALING = 0.8
ENEMY_SCALING = 0.6

GRAVITY = 14
MOVE_SPEED = 8
JUMP_SPEED = 32
LADDER_SPEED = 4

COYOTE_TIME = 0.1
JUMP_BUFFER = 0.3

CAMERA_LERP = 0.12

RECORD_FILE = "highscore.json"